<?xml version="1.0"?>
<package format="3">
  <name>amr_bringup</name>
  <version>0.1.0</version>
  <description>Launch files for Guide AMR dummy and hardware systems.</description>
  <maintainer email="team@example.com">Kookmin Robotics</maintainer>
  <license>Apache-2.0</license>
  <buildtool_depend>ament_python</buildtool_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>amr_dummy</exec_depend>
  <exec_depend>amr_safety_node</exec_depend>
  <exec_depend>amr_monitoring_adapter</exec_depend>
  <exec_depend>amr_perception</exec_depend>
  <exec_depend>amr_mcu_bridge</exec_depend>
  <exec_depend>amr_audio</exec_depend>
  <exec_depend>amr_navigation</exec_depend>
  <exec_depend>amr_vision</exec_depend>
  <export><build_type>ament_python</build_type></export>
</package>
